### ISSUE TITLE
race conditions

### ISSUE THREAD

**Issue by jkbzh** [pchampin/minutes_to_gh#5]
What happens if two or more groups are attempting to run the script in parallel. Does the github API allow to have more than one concurrent access with the same token?

I know it's an edge case, but good to know what would be the plan.

One way to handle this would be to go through a message-queue (not provided by the script but part of the system / 3rd party) so that it feeds the requests sequentially to the script.

**Comment by pchampin** [comment]
as a REST API, I assume that the GitHub API is stateless, so this should not be a problem, should it??

**Comment by jkbzh** [comment]
If your script is stateless, then this is not a problem.

**Comment by pchampin** [comment]
More precisely, [my comment above](https://github.com/pchampin/minutes_to_gh/issues/5#issuecomment-2372496340) was a response to

> Does the github API allow to have more than one concurrent access with the same token?

Now, regarding this comment:

> If your script is stateless, then this is not a problem.

Strictly speaking, the script is not entirely stateless: for each issue, it makes two related requests to the GitHub API:

* one request to get the comments on this issue, then
* one request to post a new comment ONLY IF the link to the minutes was not found in the result of the first request.

But on a given IRC channel, the operations of the bot are atomic: the bot will not start a new operation before the previous one is finished. Since operations on different channels are independent from each other (they process different minutes), I think this excludes any race condition internal to the script.

Of course, there could be a race condition between the IRC bot and another agent posting comments to the issue (possibly a 2nd instance of the bot, or someone running the script locally), but I don't think this is an issue we can address (does GitHub allows us to "lock" an issue?), nor should address (we can not control the outside world, and the worst that can happen anyway is two redundant comments in the thread of the issue).

**Comment by pchampin** [comment]
@jkbzh do you object to closing this issue?
